#!/bin/bash
# Generate docker-compose.users.yml for user frontend containers
# Uses NUM_USERS from .env (default: 20)
# Implements batched startup with health checks (GitHub Issue #17)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_FILE="$PROJECT_DIR/docker-compose.users.yml"

# Load NUM_USERS from .env if it exists
if [ -f "$PROJECT_DIR/.env" ]; then
    source "$PROJECT_DIR/.env"
fi
NUM_USERS="${NUM_USERS:-20}"
BATCH_SIZE=5  # Number of users per batch

echo "Generating docker-compose.users.yml for $NUM_USERS users..."
echo "Batch size: $BATCH_SIZE users per batch"
echo "Total batches: $((($NUM_USERS + $BATCH_SIZE - 1) / $BATCH_SIZE))"

cat > "$OUTPUT_FILE" << 'HEADER'
# Auto-generated user frontend services
# Generated by: scripts/generate-user-compose.sh
# DO NOT EDIT MANUALLY - regenerate with: ./scripts/generate-user-compose.sh
#
# Implements batched startup (GitHub Issue #17):
# - Batch leaders (user001, user006, user011, user016) start in parallel
# - Within each batch, containers start sequentially with health checks
# - Total startup time: ~2-3 minutes for 20 users
# - Command: docker compose up -d

services:
HEADER

# Generate service for each user
for i in $(seq 1 $NUM_USERS); do
    USER_ID=$(printf "user%03d" $i)
    PORT=$((8187 + i))  # user001 = 8188, user002 = 8189, etc.

    # Determine if this is a batch leader (first user of a batch)
    # Batch leaders: user001, user006, user011, user016, ...
    IS_BATCH_LEADER=$(( ($i - 1) % $BATCH_SIZE == 0 ))

    # Determine previous user for dependency chain
    if [ $i -gt 1 ] && [ $IS_BATCH_LEADER -eq 0 ]; then
        PREV_USER=$(printf "user%03d" $((i - 1)))
    else
        PREV_USER=""
    fi

    # Start writing service definition
    cat >> "$OUTPUT_FILE" << EOF
  $USER_ID:
    image: comfyume-frontend:v0.11.0
    container_name: comfy-$USER_ID
    ports:
      - "127.0.0.1:$PORT:8188"
    environment:
      - USER_ID=$USER_ID
      - QUEUE_MANAGER_URL=http://queue-manager:3000
EOF

    # Add depends_on
    if [ $IS_BATCH_LEADER -eq 1 ]; then
        # Batch leaders depend on queue-manager
        cat >> "$OUTPUT_FILE" << EOF
    depends_on:
      queue-manager:
        condition: service_healthy
EOF
    elif [ -n "$PREV_USER" ]; then
        # Batch members depend on previous user
        cat >> "$OUTPUT_FILE" << EOF
    depends_on:
      $PREV_USER:
        condition: service_healthy
EOF
    fi

    # Add volumes
    cat >> "$OUTPUT_FILE" << EOF
    volumes:
      - \${OUTPUTS_PATH}:/outputs
      - \${INPUTS_PATH}:/inputs
      - \${WORKFLOWS_PATH}:/workflows:ro
      - \${MODELS_PATH}:/models:ro
      - ./data/user_data/$USER_ID:/comfyui/user
      - ./data/user_data/$USER_ID/comfyui/custom_nodes:/comfyui/custom_nodes
EOF

    # Add health check
    cat >> "$OUTPUT_FILE" << EOF
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8188/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
EOF

    # Add network and resource limits
    cat >> "$OUTPUT_FILE" << EOF
    networks:
      - comfy-network
    restart: unless-stopped
    cpus: 1.0
    mem_limit: 2G

EOF
done

echo ""
echo "✅ Generated $OUTPUT_FILE with $NUM_USERS user services"
echo ""
echo "📦 Batched Startup Configuration:"
echo "   - Batch size: $BATCH_SIZE users per batch"
echo "   - Total batches: $((($NUM_USERS + $BATCH_SIZE - 1) / $BATCH_SIZE))"
echo "   - Batch leaders (start in parallel): user001, user006, user011, user016"
echo "   - Each batch uses sequential startup with health checks"
echo ""
echo "🚀 To start all containers:"
echo "   docker compose up -d"
echo ""
echo "📝 Note: docker-compose.yml includes this file automatically"
